### ISSUE TITLE
Error in rep(NA, nrow(gem)) : invalid 'times' argument Calls: Run_scID -> scid_multiclass -> scID_weight

### ISSUE THREAD

**Issue by tabdelaal** [BatadaLab/scID#1]
Dear all,

I was testing a cross validation on the Zhang 10x PBMC dataset using scID, and I got the following error

Error in rep(NA, nrow(gem)) : invalid 'times' argument
Calls: Run_scID -> scid_multiclass -> scID_weight

After long debugging, I found that it happened by coincidence for one cell types that the Seurat FindAllMarkers function found only one DE gene, and in scid_mutilclass line 120

weights[[as.character(celltypes[i])]] <- scID_weight(target_gem_norm[signature_genes, ], putative_groups$in_pop, putative_groups$out_pop)

R automatically change 'target_gem_norm[signature_genes, ]' to a vector as it only has one row, then in the first line in 'scID_weight' function

weights <- rep(NA, nrow(gem))

nrow(gem) is now NULL, I suggested to add 'drop=FALSE' to avoid such error:

weights[[as.character(celltypes[i])]] <- scID_weight(target_gem_norm[signature_genes, ,drop=FALSE], putative_groups$in_pop, putative_groups$out_pop)

Thank you,
Tamim

**Comment by tabdelaal** [comment]
Same goes for line 139

weighted_gem <- weights[[as.character(celltypes[i])]] * target_gem_norm[signature, ,drop=FALSE]

**Comment by kboufea** [comment]
Hi Tamim, 

Many thanks for spotting this. 
I've updated the main function and hope this resolves your issue now. If not could you please let me know which parameters you are using so that I am able to reproduce the error?

Best, 
Katerina

**Comment by tabdelaal** [comment]
Hi Katerina,

Thanks for updating the function, it solves the error I got.
I think the same change can be done to line 111

weights[[as.character(celltypes[i])]] <- scID_weight(reference_gem_norm[signature_genes, ,drop=FALSE], IN, OUT)

In case the reference is used for weights.

Bests,
Tamim
