### ISSUE TITLE
Error in svd(data, nu = 0) : a dimension is zero

### ISSUE THREAD

**Issue by K-Ramachandra-Murthy** [BatadaLab/scID#5]
Hi,
I am running the following code with target_gem and reference_gem datasets provided by the authors:

target_gem <- readRDS(file="CellType_ClassificationModels/scID/ExampleData/target_gem.rds")
reference_gem <- readRDS(file="CellType_ClassificationModels/scID/ExampleData/reference_gem.rds")
reference_clusters <- readRDS(file="CellType_ClassificationModels/scID/ExampleData/reference_clusters.rds")

scID_output <- scid_multiclass(target_gem = target_gem, reference_gem = reference_gem, reference_clusters = reference_clusters, 
                               logFC = 0.6, only_pos = FALSE,  estimate_weights_from_target = T)

I encountered the following error:

Stage 1: extract signatures genes from reference clusters
Attaching SeuratObject

Attaching package: ‘Seurat’

The following object is masked from ‘package:SummarizedExperiment’:

    Assays

Warning: The following arguments are not used: row.names
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
  |===========================================================================================================================================| 100%
Stage 2: Estimate weights of signature genes from target
    __  ___________    __  _____________
   /  |/  / ____/ /   / / / / ___/_  __/
  / /|_/ / /   / /   / / / /\__ \ / /   
 / /  / / /___/ /___/ /_/ /___/ // /    
/_/  /_/\____/_____/\____//____//_/    version 5.4.7
Type 'citation("mclust")' for citing this R package in publications.

Attaching package: ‘mclust’

The following object is masked from ‘package:MAST’:

    defaultPrior

Error in svd(data, nu = 0) : a dimension is zero
In addition: Warning message:
package ‘Seurat’ was built under R version 4.1.1

**Comment by kboufea** [comment]
Hi, 
Thanks for reporting the issue. The package had not been updated for a while and did not reflect recents changes in `Seurat`. I have made some updates now that should resolve this error. Please let me know if you still encounter issues.

**Comment by K-Ramachandra-Murthy** [comment]
Hi,
Unfortunately, error is still existed:

Stage 1: extract signatures genes from reference clusters
Warning: The following arguments are not used: row.names
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
  |===========================================================================================================================================| 100%
Stage 2: Estimate weights of signature genes from target
    __  ___________    __  _____________
   /  |/  / ____/ /   / / / / ___/_  __/
  / /|_/ / /   / /   / / / /\__ \ / /   
 / /  / / /___/ /___/ /_/ /___/ // /    
/_/  /_/\____/_____/\____//____//_/    version 5.4.7
Type 'citation("mclust")' for citing this R package in publications.

Attaching package: ‘mclust’

The following object is masked from ‘package:MAST’:

    defaultPrior

Error in svd(data, nu = 0) : a dimension is zero

**Comment by kboufea** [comment]
Hi, could you please let me know what version of scID you are using? You should have v2.2 if you re-installed the package after the updates which should resolve the error.
Thank you

**Comment by K-Ramachandra-Murthy** [comment]
Hi,
I reinstalled the scID and the issues is resolved.
Thank you
