### ISSUE TITLE
Unassigned scID labels and scID labels not matching to maximum score per cell

### ISSUE THREAD

**Issue by SalendraSingh** [BatadaLab/scID#6]
Hi All, 
Great work with the scID. I have been trying to implement the tool for one of my research. The problem I am facing is that some cells are getting assigned as "Unassigned" which I understand from code are the cells with scores as NA for all the proposed cell types. but when I am checking the score matrix provided by scID, I can see there is a numerical score for all cell labels. that made me check if the cell label with the maximum score matches the provided Cell labels. and they don't match. so I am a bit confused with the scores and the provided labels and would like some clarity over it. Any help in this regard would be appreciable. 

Thanks a lot in advance. 

Salendra Singh

**Comment by kboufea** [comment]
Hi, 

Apologies for the very late response. If it's still of interest, all cells get a score for each signature and a multimodal distribution is fitted to find the cells with the highest scores that are labelled as the cell type of the signature. Cells that are not assigned to any of the tested cell types, or are assigned to multiple cell types are finally labelled as "Unassigned". The score a cell gets for each signature depends on a few factors, including the length of the signature (the number of genes included), the proportion of positive and negative markers as wells as the dropout probablity of each gene in the signature. It  is thus not possible to compare scores of a cell across signatures but only scores of a signature across all cells. This is explained in our manuscript as well https://www.sciencedirect.com/science/article/pii/S2589004220300985.

Please let me know if you need more details and again sorry for the delayed response. 

Best, 

Katerina
